spring.datasource.url=jdbc:postgresql://localhost:5432/gestionrh
spring.datasource.username=postgres
spring.datasource.password=imane123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imanegbadamassi@gmail.com
spring.mail.password=jpzfgftgvyykibhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=homintec_secret_key_super_longue_2024_rh_platform
jwt.expiration=86400000

server.address=0.0.0.0
server.port=8080

logging.level.com.memoire.gestionrh.Security.JwtFilter=DEBUG
spring.profiles.active=default
